### ISSUE TITLE
抛弃了webpack，那周边的配件也没了吧。。

### ISSUE THREAD

**Issue by kuckboy1994** [vitejs/create-vite-app#1]
例如我想用个cssModule,sas之类的。我该怎么配置？再单独配置一个sass也太费劲了吧

**Comment by yyx990803** [comment]
看文档。

**Comment by Lsw931102** [comment]
你好，请问你解决使用scss module的用法了吗

**Comment by kuckboy1994** [comment]
@Lsw931102 https://github.com/vitejs/vite#css-modules
