### ISSUE TITLE
Feature Request: add jest and eslint for react and react-ts

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vitejs/create-vite-app#11]
Create-react-app has lint, and unit tests.
I want to add jest and eslint to the react and react-ts template.
Can I create a PR for this?

**Comment by yyx990803** [comment]
That's out of scope for Vite. We don't want to cover things that are not intrinsically related to Vite.

**Comment by xiaoxiangmoe** [comment]
@yyx990803 Can we support custom template url for vite？
