### ISSUE TITLE
使用npx create-vite-app --template react my-react-project会创建一个--template文件夹

### ISSUE THREAD

**Issue by xlzy520** [vitejs/create-vite-app#2]
而且把名字放在前面，创建的也是vue的模板

**Comment by kuckboy1994** [comment]
@xlzy520 我是ok的

**Comment by yyx990803** [comment]
Cannot reproduce. What's your OS/Node/npm version?

**Comment by xlzy520** [comment]
对不起，忘记给详细信息了。
因为在同事电脑上也是一样的情况。我明天再试一下之后，把信息贴上。

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/82529599-f5744600-9b6d-11ea-85f9-1e8d577b53fa.png)
OS: Mac Os  mojave 10.14.6
Node:  10.19.0
npm: 6.13.4

**Comment by yyx990803** [comment]
太奇怪了... 难道是 minimist 的 bug？
我系统几乎一样，无法复现...

**Comment by xlzy520** [comment]
我在本地调试一下看看行不行，直接clone下来，然后link吗

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/82631184-7c392980-9c27-11ea-85ef-b9a67e346a14.png)
node执行就没事，npx就有问题

**Comment by Chastrlove** [comment]
> 而且把名字放在前面，创建的也是vue的模板

npx同样问题，用yarn create vite-app --template react my-react-project没问题

**Comment by daychongyang** [comment]
> ![image](https://user-images.githubusercontent.com/28336270/82631184-7c392980-9c27-11ea-85ef-b9a67e346a14.png)
> node执行就没事，npx就有问题

我注意到, 分别使用 `yarn create` 跟 `npx` 完成项目创建之后的提示, 也就是 `Done. Now run: ` 后面的内容 是不一致的. 但是我在版本库里面只看到了一次提交. @yyx990803  这边是有覆盖过么.

**Comment by Jancat** [comment]
+1

npm 配置了 `--template react` 还是创建的 vue 项目
 
```sh
npm init vite-app test --template react
npm init vite-app --template react test
```

Node: v15.3.0
Mac OS: 11.0.1
npm: 7.0.14


用 yarn 就正常：
```sh
yarn create vite-app --template react test
```

**Comment by ctuu** [comment]
这实际上是 npm 对命令行参数的处理策略导致的
npm 截获了 `--template` 参数并将其设为 `process.env.npm_config_template=true`

所以 process.argv 里面的 `--template`  参数就没了
具体说明在 [config | NPM Docs](https://docs.npmjs.com/cli/v6/using-npm/config)

解决方法在链接里也有提到，加个 `--` 停止 npm 的解析
``` sh
npm init vite-app my-react-project -- --template react
```

**Comment by underfin** [comment]
@Jancat Can you give me some feedback with #56, is it works for you?

**Comment by yyx990803** [comment]
It does work for me even without the `--`... could be an npm version issue or a OS related issue. But either way adding the `--` should work.

**Comment by underfin** [comment]
> But with additional -- will create a vue template, while delete it will create react template. Anyone can help to reproduce?
 
Thanks for feadback with https://github.com/vitejs/create-vite-app/pull/59#issuecomment-741622519. This workaround caused other issues for already worked users, reopen it to contine disscuss this.

**Comment by ctuu** [comment]
According to:
https://github.com/vitejs/create-vite-app/blob/c42ca1624b442bef0e14e92202f7233b8071299c/index.js#L24

so I just print `argv` 

I write a [test](https://github.com/ctuu/npm-cli-test) and run it on GitHub Codespaces.

here is the result:

<img width="712" alt="Snipaste_2020-12-09" src="https://user-images.githubusercontent.com/22322656/101624447-e515b100-3a54-11eb-9855-4e6366f970c5.png">

**Comment by underfin** [comment]
=.= Oh, this workaround is only work for the user which has this issue, neither all users. Sorry for mistaken reopen.
