### ISSUE TITLE
Fragment already declare issue

### ISSUE THREAD

**Issue by Innei** [vitejs/create-vite-app#22]
It looks like Vite will automatically inject `Fragment`, so I needn't import this manually, but if I didn't import this, ide will highlight this error, say `Fragment is not defined.`, so I can use only syntactic sugar, `<> </>`. but, if i need to add key or other property, how can I do.

My suggestion is that if there are already has `Fragment` in the scope, cancel automatic injection.

```
App.tsx:20 Uncaught SyntaxError: Identifier 'Fragment' has already been declared
```

**Comment by underfin** [comment]
Can you please an reproduction for this?

**Comment by Innei** [comment]
```tsx
import {
  defineComponent,
  Fragment,
} from 'vue'
export default defineComponent({
  name: 'App',
  setup() {
    return () => <Fragment><div className="">test</div></Fragment>
  },
})
```

```
Uncaught SyntaxError: Identifier 'Fragment' has already been declared
```

But, if remove the `Fragment` import from 'vue', it worked.
```ts
import {
  defineComponent,
  Fragment, // remove this, it work.
} from 'vue'
```

**Comment by Innei** [comment]
Or, just use `<>`

```tsx
 setup() {
    return () => (
      <>
        <div className="">test</div>
      </>
    )
  },
```

**Comment by underfin** [comment]
What library do you used vue with `jsx`? Look like it is their issues.

**Comment by Innei** [comment]
```json
{
  "compilerOptions": {
    "jsx": "preserve"
  }
}
```

**Comment by yyx990803** [comment]
Just use `<></>` or `() => [<div/>, <div/>]`. There's no point to import `Fragment` if you are using JSX, that's intended.
