### ISSUE TITLE
React Fast Refresh broken with reason-react template v0.20.0

### ISSUE THREAD

**Issue by hamza0867** [vitejs/create-vite-app#25]
I believe the HMR for react is broken with this template.
Whenever I change anything in my source code, the whole page reloads, instead of just updating the parts that need to. I don't know if this is a problem with vite-plugin-react 2.0 or with vite.

Please can you confirm that HMR is indeed broken for react or did it just break with reason ?

Thank you guys so much for your work on vite, it is AWESOME :heart:

**Comment by yyx990803** [comment]
Just checked with 0.20.7 and it seems to be working as expected.

**Comment by hamza0867** [comment]
@yyx990803 with the react-template ??

**Comment by hamza0867** [comment]
My bad I apologize, it is working. Thank you again for the great work on vite :heart:
