### ISSUE TITLE
HMR not working with reason-react

### ISSUE THREAD

**Issue by jisensee** [vitejs/create-vite-app#34]
Not quite sure if this should be here or in the react-plugin/vite repo but I noticed that HMR does not work anymore since the latest beta releases.

### Reproduction
Just create a new vite app with the reason-react template and run it, no other steps needed. Changes in the .re files always trigger a full page refresh. On vite 0.20.10 and plugin 2.x, this would hot replace the modules instead. Since the beta releases this doesnt work anymore.
Only testet on Windows so far.

**Comment by yyx990803** [comment]
fixed in `vite-plugin-react@3.0.1`
