### ISSUE TITLE
[vue] valid template root

### ISSUE THREAD

**Issue by boskiv** [vitejs/create-vite-app#37]
I have linter error on fresh generated project 
```
[vue/valid-template-root]
The template root requires exactly one element.eslint-plugin-vue
```

Does vue-3 changed the rule of one root element in template ?

```
<template>
  <h1>{{ msg }}</h1>
  <button @click="count++">count is: {{ count }}</button>
  <p>Edit <code>components/HelloWorld.vue</code> to test hot module replacement.</p>
</template>
```

Should it be wrapped with div ?
```
<template>
  <div>
      <h1>{{ msg }}</h1>
      <button @click="count++">count is: {{ count }}</button>
      <p>Edit <code>components/HelloWorld.vue</code> to test hot module replacement.</p>
  </div>
</template>
```

**Comment by yyx990803** [comment]
Vite is using Vue 3 which supports multiple root elements. Vetur or the linter you are using isn't updated to allow that yet. If you are using eslint-plugin-vue, Just disable the rule.

**Comment by boskiv** [comment]
btw, I'm using just a scaffolded app 
```
npm init vite-app <project-name>
```

**Comment by yyx990803** [comment]
The app itself doesn't care about linters and there's nothing wrong with it. It's your IDE configuration doesn't know it's a Vue 3 app.
