### ISSUE TITLE
Feature Request: Preconfigured stuffs like vue-cli

### ISSUE THREAD

**Issue by SeyyedKhandon** [vitejs/create-vite-app#39]
**What problem does this feature solve?**
 
At the moment, `yarn create vite-app my_app`, creates a bare scaffolded project with simply supporting Vue.  
As you know a real project needs more packages and configurations like unit-testing, babel, router, SCSS loader, etc...

It will be great if it works like `vue-cli` and does the configuration behind the  scene like `vue-cli` after asking what the user wants:

![image](https://user-images.githubusercontent.com/59599950/88650543-0d23f980-d0de-11ea-8d27-2759f1a1b53b.png)

Thank you in advance for your and your teams great works. 

keep up the good work.

**Comment by yyx990803** [comment]
This is explicitly out of scope for this tool. It's really just a glorified git repo fetcher and I have no intention in making it into another `vue-cli`.
