### ISSUE TITLE
1 command line instead for more faster create project , enter project, lanuch project .

### ISSUE THREAD

**Issue by ghost** [vitejs/create-vite-app#46]
`vite-app <project name>`

Is possible just use 1 command line instead 4 command lines ? 

it's really hard to remember and understand use npm init to create vite-app !???? 
Why we have to manually click keyboard cd project folder and lanuch project, and wait, wait ,wait. wast of time.

**Comment by ghost** [comment]
`vite <project name> `

can't be long more.

**Comment by yyx990803** [comment]
You can create your own tool for this, but `create-vite-app` will just be fetching templates and nothing more.
