### ISSUE TITLE
can you add "template-vue-ts"?

### ISSUE THREAD

**Issue by snowdream** [vitejs/create-vite-app#48]
I want to create the project built on Vue3 and TypeScript.

**Comment by mikeshi80** [comment]
Just rename the main.js to main.ts, and add lang props in your script tag, set it to "ts".

Typescript is the superset of javascript, so it will run correctly, you can make the code more tyepscript later.

Because it is really small modification for developers, I think this is dispensable.

**Comment by 0x6a68** [comment]
@snowdream what changes do you think are needed? (based on template `vue`)

**Comment by snowdream** [comment]
@0x6a68 you can check this pull request.

https://github.com/vitejs/create-vite-app/pull/17
