### ISSUE TITLE
Feature Request: how to customize my own template?

### ISSUE THREAD

**Issue by BaconZhang** [vitejs/create-vite-app#53]
Vite is really good. However, I want to create my own template and use this template to create many projects. Without this feature I have to do many repeat works. Any solution or plan for this feature?

**Comment by yyx990803** [comment]
`create-vite-app` is just a collection of official templates. For custom ones, just use a github repo + https://github.com/Rich-Harris/degit

**Comment by BaconZhang** [comment]
Thanks
